version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    working_directory: ~/app
    environment:
      NODE_ENV: development
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      DOCKER_USERNAME: $DOCKER_USERNAME
      DOCKER_PASSWORD: $DOCKER_PASSWORD

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: npm install

